package sprint1;

// Reference: https://spring.io/guides/gs/accessing-data-jpa/

import java.net.URL;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class EventDetails {
    
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private long id;
    private String name;
    private String category;
    private String description;
    private String location;
    private long organizerId;
    private URL thumbnailImageURL; 
    private URL imageURL;
    private Date startDate;
    private Date endDate;
    private int totalTickets;
    private int ticketsBooked;
    private double ticketPrice;

    // Getters and Setters. Needed? Getters needed for JSON and Setters needed for modify

    protected EventDetails() {} // For JPA

    // TODO Starting with few details.
    public EventDetails(String name, String category, String description, String location,
                        long organizerId, URL thumbnailImageURL, URL imageURL, Date startDate,
                        Date endDate, int totalTickets, double ticketPrice) {
        this.name = name;
        this.category = category;
        this.description = description;
        this.location = location;
        this.organizerId = organizerId;
        this.thumbnailImageURL = thumbnailImageURL;
        this.imageURL = imageURL;
        this.startDate = startDate;
        this.endDate = endDate;
        this.totalTickets = totalTickets;
        this.ticketsBooked = 0;
        this.ticketPrice = ticketPrice;
    }

    public long getId() {
        return this.id;
    }
    
    // No setId() because it is autogenerated. 

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCategory() {
        return this.category;
    }

    public void setCategory(String category) {
        this.category = category;
    }
    
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
    
    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }
    
    public long getOrganizerId() {
        return this.organizerId;
    }

    // No setOrganizerId() as it in unclear if it
    // should possible to transfer event from one organizer to another.
    
    public URL getThumbnailImageURL() {
        return this.thumbnailImageURL;
    }

    public void setThumbnailImageURL(URL thumbnailImageURL) {
        this.thumbnailImageURL = thumbnailImageURL;
    }
    
    public URL getImageURL() {
        return this.imageURL;
    }
    
    public void setImageURL(URL imageURL) {
        this.imageURL = imageURL;
    }
    
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public int getTotalTickets() {
        return this.totalTickets;
    }
    
    public void setTotalTickets(int totalTickets) {
        this.totalTickets = totalTickets;
    }
    
    public int getTicketsBooked() {
        return this.ticketsBooked;
    }
    
    public double getTicketPrice() {
        return this.ticketPrice;
    }

    public void setTicketPrice(double ticketPrice) {
        this.ticketPrice = ticketPrice;
    }

    @Override
    public String toString() {
        // TODO A proper toString() implementation.
        return "[" + this.name + ", " + this.startDate + "]";
    }
}